default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user-posts-app_development

test:
  <<: *default
  database: user-posts-app_test

# production:
#   <<: *default
#   database: user-posts-app_production
#   username: user-posts-app
#   password: <%= ENV['USER-POSTS-APP_DATABASE_PASSWORD'] %>
